#ifndef CoCoA_PREPROCESSOR_DEFNS_H
#define CoCoA_PREPROCESSOR_DEFNS_H

// Created automatically by CoCoALib configure script.
// Created on date  2018-08-09  at time  10:16:36

// To enable debugging, reconfigure with option "--debug"
#undef CoCoA_DEBUG

// define CoCoA_MEMPOOL_DEBUG if you have memory problems
#undef CoCoA_MEMPOOL_DEBUG


#define CoCoA_ULONG2LONG 1
#undef CoCoA_THREADSAFE_HACK
#define CoCoA_WITH_BOOST
#undef CoCoA_WITH_NORMALIZ
#undef CoCoA_WITH_FROBBY
#undef CoCoA_WITH_GFAN
#undef CoCoA_WITH_MATHSAT
#undef CoCoA_WITH_GSL

#endif
